version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: db_tasksave
    restart: always
    environment:
      POSTGRES_USER: ADMIN
      POSTGRES_PASSWORD: vhWzeEoUw0OwsL
      POSTGRES_DB: tasksave_test
    ports:
      - "5432:5432"
    networks:
      - tasksave_network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "ADMIN", "-d", "tasksave_test"]
      interval: 5s
      timeout: 5s
      retries: 5


  tasksave_api:
    build: .
    container_name: api_tasksave
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      JWT_ACCESS_SECRET: GFwm11PeX3hXCY
      JWT_REFRESH_SECRET: XqkebSG21JR1lh
      JWT_RESCUE_SECRET: ESggO6VcIxWytY
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tasksave_test
      SPRING_DATASOURCE_USERNAME: ADMIN
      SPRING_DATASOURCE_PASSWORD: vhWzeEoUw0OwsL
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: noreply.tasksaveapp@gmail.com
      SPRING_MAIL_PASSWORD: aznxfeznzklwzqwb
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./storage:/app/storage

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123@
    networks:
      - tasksave_network
    depends_on:
      - postgres

networks:
  tasksave_network:
