version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: db_tasksave
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: tasksave
    ports:
      - "5432:5432"


  tasksave_api:
    build: .
    container_name: api_tasksave
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tasksave
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data:
